### ISSUE TITLE
[Improvement] generate bundle_name in `syndicate assemble` command if not provided

### ISSUE THREAD

**Issue by bohdan-onsha** [epam/aws-syndicate#141]
Add ability to generate bundle_name in `syndicate assemble` command if not provided. 

Just need to change `bundle_name` attribute callback to `generate_default_bundle_name` (used by `syndicate build`)

**Comment by dmytro-afanasiev** [comment]
These changes were made in Thursday but I seem to forget to make a pull request. [Here](https://github.com/epam/aws-syndicate/pull/145) it is:
