### ISSUE TITLE
[FR] Python meta generation

### ISSUE THREAD

**Issue by Dmytro-Skorniakov** [epam/aws-syndicate#24]
**Is your feature request related to a problem? Please describe.**

At the moment only Java is supported for the metadata generation. There are a lot of projects written in Python that is more adapted to developing Serverless applications. But now aws-syndicate allows us to bootstrap development only for Java projects. We need to support metadata generation for Python-based lambdas.

**Describe the solution you'd like**

I guess it can be some format of Python docstring that will contain all required fields. Like this:

"""
lambda_name: my_own_lamblda
role_name: role name
"""

**Describe alternatives you've considered**

Another way for configuration declaration - decorators. But it will be executed every time during lambda invocation.

**Comment by ttrzcinski** [comment]
So Oleksandr, You are developing the solution or just thinking about it? Can this be re-assigned?

**Comment by oleksandr-onsha** [comment]
> So Oleksandr, You are developing the solution or just thinking about it? Can this be re-assigned?

Hi. I actually have some drafts of this. Branch 'generate_python_meta'. Use it if it will be useful for you. Now I am not developing it. 

Do you use aws-syndicate on your project (maybe pet one:) ?
