### ISSUE TITLE
[Improvement] Add ability to set integration request parameters in deployment_resources.json

### ISSUE THREAD

**Issue by Polina-Prakhova** [epam/aws-syndicate#76]
**Is your feature request related to a problem? Please describe.**
While describing API Gateway in deployment_resources.json there is no ability to specify integration request parameters (headers, query string, path).

**Describe the expected profit**
Ability to specify integration request parameters automatically.

**Describe the solution you'd like**
Add new optional parameter in deployment_resources named `integration_request_parameters`, value must match the pattern of `integration.request.{location}.{name}`.

**Comment by lastiq** [comment]
The functionality has been merged to the master branch and will be released in version 0.9.5.
