### ISSUE TITLE
[BUG] Update Java version in Travis builds

### ISSUE THREAD

**Issue by bohdan-onsha** [epam/aws-syndicate#85]
**Describe the bug**
All of the Travis builds fail due to the deprecated version of Java used for SonarQube Scanner.

**To Reproduce**
Trigger any aws-syndicate Travis build.

**Screenshots**
Example Job log:
<img width="871" alt="Screenshot 2021-03-13 at 20 30 51" src="https://user-images.githubusercontent.com/31548234/111040297-06fb4700-843b-11eb-9068-24d6ca8cee4f.png">

**Comment by lastiq** [comment]
Fixed in aws-syndicate v.0.9.5
